---
stages:
  - linting
  - release

variables:
  EXECUTABLE_NAME: dockup
  IMAGE_NAME: ${CI_REGISTRY_IMAGE}

linting:
  stage: linting
  image: python:latest
  script:
    - pip install -r requirements.txt
    - pip install isort black flake8 pylint
    - isort ${EXECUTABLE_NAME} --check-only
    - black ${EXECUTABLE_NAME} --check --diff --line-length 79
    - flake8 ${EXECUTABLE_NAME}
    # - pylint ${EXECUTABLE_NAME} --disable=C0111

release:
  image: docker:latest
  services:
    - docker:dind
  stage: release
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - export TAG="${CI_COMMIT_TAG:-latest}" && echo $TAG
    - docker build -t ${IMAGE_NAME}:${TAG} .
    - docker push ${IMAGE_NAME}:${TAG}
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: on_success
    - if: $CI_COMMIT_TAG
      when: on_success
...
