---
name: dockup
services:
  dockup:
    image: ramiuslr/dockup:latest # You should set a fixed tag
    container_name: dockup
    restart: always
    ports:
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      DOCKUP_INTERVAL: 5 # Defaults to 30
...
